# Generated by Django 5.2.8 on 2025-11-29 14:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("centroid", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("radius_meters", models.IntegerField(default=100)),
                ("event_count", models.IntegerField(default=1)),
                ("first_event_at", models.DateTimeField(auto_now_add=True)),
                ("last_event_at", models.DateTimeField(auto_now=True)),
                (
                    "computed_severity",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                            (4, "Critical"),
                        ],
                        default=1,
                        help_text="Boosted severity based on event count",
                    ),
                ),
            ],
            options={
                "db_table": "event_cluster",
                "indexes": [
                    models.Index(fields=["centroid"], name="idx_cluster_centroid"),
                    models.Index(
                        fields=["-computed_severity"], name="idx_cluster_severity"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reports_submitted", models.IntegerField(default=0)),
                ("reports_verified", models.IntegerField(default=0)),
                ("badges", models.JSONField(blank=True, default=list)),
                ("reputation_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("media_url", models.URLField(blank=True, max_length=500)),
                (
                    "media_type",
                    models.CharField(
                        blank=True,
                        choices=[("image", "Image"), ("video", "Video")],
                        max_length=10,
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("emergency", "Emergency"),
                            ("security", "Security"),
                            ("traffic", "Traffic"),
                            ("protest", "Protest/Gathering"),
                            ("infrastructure", "Infrastructure"),
                            ("environmental", "Environmental"),
                            ("informational", "Informational"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subcategory", models.CharField(blank=True, max_length=50)),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                            (4, "Critical"),
                        ],
                        default=1,
                    ),
                ),
                ("ai_confidence", models.FloatField(blank=True, null=True)),
                ("ai_reasoning", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewing", "Reviewing"),
                            ("verified", "Verified"),
                            ("resolved", "Resolved"),
                            ("false_alarm", "False Alarm"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="core.eventcluster",
                    ),
                ),
            ],
            options={
                "db_table": "event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["location"], name="idx_event_location"),
                    models.Index(fields=["-created_at"], name="idx_event_created_at"),
                    models.Index(
                        fields=["status", "-severity"], name="idx_event_status_severity"
                    ),
                    models.Index(fields=["category"], name="idx_event_category"),
                ],
            },
        ),
    ]
