# Generated by Django 5.2.8 on 2025-11-29 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventcluster",
            options={"ordering": ["-computed_severity", "-last_event_at"]},
        ),
    ]
