# Generated by Django 5.2.8 on 2025-11-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_eventcluster_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="transcription",
            field=models.TextField(
                blank=True, help_text="AI-generated transcription of audio content"
            ),
        ),
    ]
